name: Daily JSON Processing

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every night
  workflow_dispatch:

jobs:
  process_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Change to 3.9

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the JSON processing script
        run: |
          python update_json.py
