name: Daily JSON Processing

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every night
  workflow_dispatch:  # Allows manual triggering via GitHub UI

jobs:
  process_json:
    runs-on: ubuntu-latest  # The environment the workflow will run in

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository so the script can run

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Upgraded Python version

      - name: Install LangChain Gemini manually
        run: |
          pip install langchain-google-gemini  # Manually install package first

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Installs dependencies from file

      - name: Run the JSON processing script
        run: |
          python update_json.py  # The script that updates or processes your JSON data
